---
- hosts: ganesha
  become: true
  tasks:
  - name: Create a mount point for Gluster
    file: path=/mnt/gluster state=directory mode=0755 owner=root group=root

  - name: Mount glusterfs
    mount: name=/mnt/gluster src={{ hostvars['gluster1']['ipv4'] }}:/volume1 fstype=glusterfs state=mounted
