---
- hosts: client
  become: true
  tasks:
  - name: Install GlusterFS repository
    apt_repository: repo=ppa:gluster/{{ gluster_repo }} state=present

  - name: Install Gluster client packages
    apt: name={{ item }} state=latest update_cache=yes
    with_items:
    - glusterfs-client
