---
- hosts: ganesha
  become: true
  tasks:
  - name: Install Ganesha repository
    apt_repository: repo=ppa:gluster/nfs-ganesha state=present

  - name: Install libntirpc repository
    apt_repository: repo=ppa:gluster/libntirpc state=present

  - name: Install GlusterFS repository
    apt_repository: repo=ppa:gluster/{{ gluster_repo }} state=present

  - name: Install Ganesha NFS packages
    apt: name={{ item }} state=latest update_cache=yes
    with_items:
    - nfs-ganesha
    - nfs-ganesha-fsal
    - glusterfs-common
    - glusterfs-client
