---
- hosts: gluster
  become: true
  tasks:
  - name: Start the Gluster service on all hosts
    service: name=glusterfs-server state=started enabled=yes

# These commands only need to run from one of the hosts. Doesn't matter which one.
- hosts: gluster[0]
  become: true
  tasks:
  - name: Create a script to probe your peers
    template: src=probe.sh.j2 dest=/root/probe.sh owner=root group=root mode=0744

  - name: Probe your peers
    shell: /root/probe.sh

# Now on all hosts...
- hosts: gluster
  become: true
  tasks:
  - name: Verify that each host in the cluster sees every other host in the cluster
    shell: gluster peer status

# Now on one host...
- hosts: gluster[0]
  become: true
  tasks:
  - name: Create a script to create a volume
    template: src=create-volume.sh.j2 dest=/root/create-volume.sh owner=root group=root mode=0744

  - name: Create a gluster volume
    shell: /root/create-volume.sh
    args:
      creates: /etc/glusterfs/volume1.created

  - name: Disable Gluster-native NFS on volume1 (We will use Ganesha for NFS access)
    shell: gluster volume set volume1 nfs.disable on

  - name: Start the GlusterFS volume
    shell: gluster volume start volume1
    args:
      creates: /data/brick1/files/.glusterfs
