---
- hosts: gluster
  become: true
  tasks:
  - name: Install GlusterFS repository
    apt_repository: repo=ppa:gluster/{{ gluster_repo }} state=present 

  - name: Install libntirpc repository
    apt_repository: repo=ppa:gluster/libntirpc state=present
  
  - name: Install GlusterFS packages
    apt: name={{ item }} state=latest update_cache=yes
    with_items:
    - glusterfs-server
