---
# These commands only need to run from one of the hosts. Doesn't matter which one.
- hosts: gfs[0]
  become: true
  tasks:
  - name: Create a script to probe your peers
    template: src=templates/probe.sh.j2 dest=/root/probe.sh owner=root group=root mode=0744

  - name: Probe your peers
    shell: /root/probe.sh

# Now on all hosts...
- hosts: gfs
  become: true
  tasks:
  - name: Verify that each host in the cluster sees every other host in the cluster
    shell: gluster peer status

# Now on one host...
- hosts: gfs[0]
  become: true
  tasks:
  - name: Create a script to create a volume
    template: src=create-volume.sh.j2 dest=/root/create-volume.sh owner=root group=root mode=0744

  - name: Create a gluster volume
    shell: /root/create-volume.sh
    args:
      creates: /etc/glusterfs/volume1.created

  - name: Enable NFS on volume1
    shell: gluster volume set volume1 nfs.disable off

  - name: Disable NFS name lookups
    shell: gluster volume set volume1 nfs.addr-namelookup off

  - name: Allow volumes to be exported
    shell: gluster volume set volume1 nfs.export-volumes on

  - name: Start the GlusterFS volume
    shell: gluster volume start volume1
    args:
      creates: /data/brick1/files/.glusterfs

  - name: Enable quotas on the volume
    shell: gluster volume quota volume1 enable && touch /etc/glusterfs/volume1.quotas.enabled
    args:
      creates: /etc/glusterfs/volume1.quotas.enabled
